version: "3.6"

services:
  indexer:
    image: dipdup/starknet-metadata:latest
    build:
      dockerfile: build/metadata/Dockerfile
      context: .
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ipfs:/etc/starknet-metadata/ipfs

  db:
    image: postgres:15
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_USER=${POSTGRES_USER:-dipdup}
      - POSTGRES_DB=${POSTGRES_DB:-starknet_metadata}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.28.0
    ports:
      - "127.0.0.1:${HASURA_PORT:-8080}:8080"
    depends_on:
      - db
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://${POSTGRES_USER:-dipdup}:${POSTGRES_PASSWORD:-changeme}@${HASURA_POSTGRES_HOST:-db}:5432/${POSTGRES_DB:-starknet_metadata}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user

volumes:
  db:
  ipfs:
